# permissions for end users to edit bookinfoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bookinfo-editor-role
rules:
- apiGroups:
  - book.example.org
  resources:
  - bookinfoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - book.example.org
  resources:
  - bookinfoes/status
  verbs:
  - get
