# permissions for end users to view bookinfoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bookinfo-viewer-role
rules:
- apiGroups:
  - bookinfo.demo.com
  resources:
  - bookinfoes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - bookinfo.demo.com
  resources:
  - bookinfoes/status
  verbs:
  - get
